# Application
quarkus.application.name=player-management-ms
quarkus.http.port=8081

# Database
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:player_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false

# JWT
mp.jwt.verify.issuer=${JWT_ISSUER:https://catoritech.com/player-management}
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem
smallrye.jwt.new-token.issuer=${JWT_ISSUER:https://catoritech.com/player-management}
smallrye.jwt.new-token.lifespan=3600

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=accept,authorization,content-type
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
